apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfe
spec:
  template:
    spec:
      containers:
      - env:
        - name: MFE_CDN_URL
          value: {{ MFE_EXTENSIONS_CDN_URL }}
        name: mfe
        volumeMounts:
        - mountPath: /openedx/bin/
          name: entrypoint
        command:
          - /openedx/bin/docker-entrypoint.sh
        args:
          - caddy
          - run
          - --config
          - /etc/caddy/Caddyfile
          - --adapter
          - caddyfile
      volumes:
      - configMap:
          defaultMode: 484
          name: mfeextensions-docker
        name: entrypoint
